"""empty message

Revision ID: 13cc8ebc0c54
Revises: 248afba8d015
Create Date: 2019-07-28 12:44:38.549185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13cc8ebc0c54'
down_revision = '248afba8d015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_id'), 'availability', ['id'], unique=False)
    op.drop_table('Availability')
    op.add_column('college_selected_package', sa.Column('availability_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'college_selected_package', 'availability', ['availability_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'college_selected_package', type_='foreignkey')
    op.drop_column('college_selected_package', 'availability_id')
    op.create_table('Availability',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Availability_id_seq"\'::regclass)'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('package_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Availability', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], name='Availability_package_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Availability_pkey')
    )
    op.drop_index(op.f('ix_availability_id'), table_name='availability')
    op.drop_table('availability')
    # ### end Alembic commands ###
