"""empty message

Revision ID: 248afba8d015
Revises: d45821cf3017
Create Date: 2019-07-24 14:01:10.767468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248afba8d015'
down_revision = 'd45821cf3017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('Availability', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Availability_id'), 'Availability', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Availability_id'), table_name='Availability')
    op.drop_table('Availability')
    # ### end Alembic commands ###
