"""empty message

Revision ID: d45821cf3017
Revises: e4f66a307b08
Create Date: 2019-07-24 13:19:01.734079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45821cf3017'
down_revision = 'e4f66a307b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.add_column('college', sa.Column('account_holder', sa.String(), nullable=True))
    op.add_column('college', sa.Column('account_no', sa.String(), nullable=True))
    op.add_column('college', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('college', sa.Column('coordiantor_name', sa.String(), nullable=True))
    op.add_column('college', sa.Column('ifsc_code', sa.String(), nullable=True))
    op.drop_column('college', 'coordiantor')
    op.add_column('student', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'date')
    op.add_column('college', sa.Column('coordiantor', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('college', 'ifsc_code')
    op.drop_column('college', 'coordiantor_name')
    op.drop_column('college', 'bank_name')
    op.drop_column('college', 'account_no')
    op.drop_column('college', 'account_holder')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
