"""empty message

Revision ID: e4f66a307b08
Revises: 78db30f29224
Create Date: 2019-07-21 03:20:17.938219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f66a307b08'
down_revision = '78db30f29224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'price')
    # ### end Alembic commands ###
